include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: juliagpu/cuda:10.1-cudnn7-cutensor1-devel-ubuntu18.04

variables:
  JULIA_CUDA_VERBOSE: 'true'


# Julia versions

julia:1.0:
  extends:
    - .julia:1.0
    - .test
  tags:
    - nvidia

julia:1.1:
  extends:
    - .julia:1.1
    - .test
  tags:
    - nvidia

# the "primary" target, where we require thorough tests
# (this requires a recent GPU)
julia:1.2:
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia
    - sm_75
  variables:
    CI_THOROUGH: 'true'

julia:1.3:
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia

julia:nightly:
  extends:
    - .julia:nightly
    - .test
  tags:
    - nvidia
  allow_failure: true


# special tests

pool:none:
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia
  variables:
    CUARRAYS_MEMORY_POOL: 'none'

pool:simple:
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia
  variables:
    CUARRAYS_MEMORY_POOL: 'simple'

pool:split:
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia
  variables:
    CUARRAYS_MEMORY_POOL: 'split'

precompile:
  extends: .julia:1.2
  image: ubuntu:bionic
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.instantiate();
                          Pkg.build();
                          Pkg.API.precompile()'

partial:
  extends:
    - .julia:1.2
    - .test
  image: nvidia/cuda:10.1-devel-ubuntu18.04
  tags:
    - nvidia


# reverse tests

# NOTE: reverse testing is tricky because of Manifests. we instantiate both, give priority
#       to this package's Manifest, and manually run tests outside of the test environment.
#       that means we have to manually install Flux' test dependencies though.

flux:
  extends: .julia:1.2
  tags:
    - nvidia
  script:
    - export FLUX="$HOME/.julia/dev/Flux"
    - julia -e 'using Pkg;
                Pkg.develop("Flux");'
    - julia --project -e 'using Pkg;
                          Pkg.instantiate()'
    - julia --project=$FLUX -e 'using Pkg;
                                Pkg.instantiate();
                                Pkg.add(["Documenter"])'
    - JULIA_LOAD_PATH=".:$FLUX::" julia $FLUX/test/runtests.jl
  allow_failure: true


# other tasks

coverage:
  extends:
    - .julia:1.2
    - .coverage

documentation:
  extends:
    - .julia:1.2
    - .documentation
  tags:
    - nvidia

pages:
  stage: deploy
  script:
    - mv docs/build public
  artifacts:
    paths:
    - public
  only:
    - master
